package com.chatservice.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Entity
@Table(
        name = "messages",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_msg_sender_client",
                        columnNames = {"senderId", "clientMessageId"}
                )
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(nullable = false)
    private String roomId;

    /**
     * ID generated by the frontend before sending.
     * Used to prevent duplicate messages when the client retries.
     * Composite unique with senderId so two users cannot collide on UUIDs.
     */
    @Column(nullable = false)
    private String clientMessageId;

    /**
     * User who sent the message.
     */
    @Column(nullable = false)
    private String senderId;


    /**
     * TEXT / IMAGE
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private MessageType type;

    /**
     * For Phase 1:
     * plain text.
     *
     * Later this will contain encrypted ciphertext.
     */
    @Column(columnDefinition = "TEXT")
    private String content;

    /**
     * Used when type = IMAGE.
     *
     * This should reference your media service/media ID,
     * not contain the actual image.
     */
    private String mediaId;

    @Column(nullable = false)
    private LocalDateTime timestamp;

    /**
     * SENT
     * DELIVERED
     * READ
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private MessageStatus status;
}