spring :
  application :
    name : apigateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: userservice
          uri: http://localhost:8080 #lb means load balancer
          predicates:
            - Path=/api/users/**

        - id: followerservice
          uri: http://localhost:8082
          predicates:
              - Path=/api/followers/**

        - id: postservice
          uri: http://localhost:8081
          predicates:
            - Path=/api/posts/**
        - id: mediaservice
          uri: http://localhost:8081
          predicates:
            - Path=/api/media/**

        - id: postinteractionservice
          uri: http://localhost:8083
          predicates:
            - Path=/api/post/interact/**

        - id: chatservice
          uri: http://localhost:8084   # your chat-service
          predicates:
              - Path=/messages/**

        - id: recommendationservice
          uri: http://localhost:8085
          predicates:
            - Path=/api/recommendations/**, /recommendation/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true


server:
  port: 8079

