spring:
  application:

    name: userservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://avnadmin:AVNS_gRyATXAHOgD_LF6tXX1@fastfoods-fastfoods.j.aivencloud.com:26790/defaultdb?ssl-mode=REQUIRED
    username: root
    password: AVNS_gRyATXAHOgD_LF6tXX1
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost