spring:
  application:
    name: chatservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://avnadmin:AVNS_gRyATXAHOgD_LF6tXX1@fastfoods-fastfoods.j.aivencloud.com:26790/defaultdb?ssl-mode=REQUIRED
    username: root
    password: AVNS_gRyATXAHOgD_LF6tXX1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8084

services:
  userserivce: http://localhost:8080/api/users/followers
